config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :doctor_specifications

  root 'appointments#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    authenticated :user do
      root 'appointments#index', as: 'authenticated'
    end
    unauthenticated :user do
      root 'sessions#new', as: 'unauthenticated'
    end
    match '/logout', to: 'devise/session#destroy', via: :all
  end

  resources :appointments do
    resource :note
  end
end

app/models/note.rb
class Note < ApplicationRecord
  # VALID_CONTENT_REGEX = /\A[a-zA-Z0-9\s]+\z/i
  # validates :description, presence: true, format: { with: VALID_CONTENT_REGEX, message: "can only contain letters and numbers." }

  belongs_to :appointment
  belongs_to :user
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_current_notes_appointment

  def create
    @note = @appointment.notes.new(notes_params)
    if @note.save
      redirect_to appointment_path(@appointment)
    else
      redirect_to appointments_path(@appointment), notice: 'Unable to add note, try again!'
    end
  end

  def edit
    @note = find_current_notes_appointment.note
  end

  def update
    @note = @appointment.notes.find(params[:id])
    if @note.update(notes_params)
      redirect_to appointment_path(@appointment), notice: 'Updated Note'
    else
      render 'edit', notice: 'Sorry, Unable to update Note, Please try again!'
    end
  end

  def destroy
    @note = find_current_notes_appointment.note
    if @note.destroy
      redirect_to root_path, notice: 'Note destroyed!'
    else
      redirect_to @note
    end
  end

  private

  def notes_params
    params.require(:note).permit(:description)
  end

  def find_current_notes_appointment
    @appointment = Appointment.find(params[:appointment_id])
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for [ @appointment, @appointment.notes.build ] do |form| %>
  <p>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>         

app/views/notes/_note.html.erb
<p>
	<strong>Description:</strong>
	<%= note.description %>
</p>

<p>
  <td><%= link_to 'edit note', edit_appointment_note_path(appointment&.id) %></td>
</p>

<p>
  <td><%= link_to 'Delete note',appointment_note_path(appointment.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</p>

app/views/notes/edit.html.erb
<h1> edit notes</h1>

<%= form_for [@note.appointment, @note] do |form| %>
  <p>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', appointments_path %>