config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :doctor_specifications

  root 'appointments#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    authenticated :user do
      root 'appointments#index', as: 'authenticated'
    end
    unauthenticated :user do
      root 'sessions#new', as: 'unauthenticated'
    end
    match '/logout', to: 'devise/session#destroy', via: :all
  end

  resources :appointments do
    resource :note
  end
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  validates :doctor_id, presence: true
  validates :patient_id, presence: true
  validates :date, presence: true
  validate  :validate_appoinment_date
  validates :time_slot_id, presence: true

  enum status: %i[pending accepted cancelled]

  belongs_to :doctor, class_name: 'User', foreign_key: 'doctor_id'
  belongs_to :patient, class_name: 'User', foreign_key: 'patient_id'
  belongs_to :time_slot
  has_one :note, dependent: :destroy
  
  accepts_nested_attributes_for :note, allow_destroy: true

  private

  def validate_appoinment_date
    if date.present?
    errors[:date] << 'please put a valid date' if date < Time.zone.now 
    end
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :find_current_appointment, except: [:index, :new, :create]

  def index
    if current_user.role == 'patient'
      @appointments = current_user.patient_appointments
    else
      @appointments = current_user.doctor_appointments
    end
  end
    
    def new 
      @appointment = Appointment.new
      @time_slots = TimeSlot.all
      @doctors = User.get_all_doctors
      @appointment.build_note
    end
  
    def create
      @appointment = Appointment.new(appointments_params)
      @appointment.patient_id = current_user.id
      if check_available_appointment(appointments_params)
        if @appointment.save!
          # UserMailer.welcome_email.deliver_now!
          redirect_to appointment_path(@appointment), notice: 'Appointment saved!'
        else
          redirect_to new_appointment_path #, notice: 'Unable to create Appointment, try again!'
        end
      else
        redirect_to new_appointment_path #, notice: 'Appointment already taken'
      end
    end

  
    def edit
      @all_doctors = User.get_all_doctors
      @time_slots = TimeSlot.all
      @slot = params["slot"]
    end
  
    def update
      
      if @appointment.update(appointments_params)
         redirect_to root_path, notice: 'Updated successfully!'
      else
        render 'edit', notice: 'Unable to save Appointment, Try again!'
      end
    end
  
    def destroy
      @appointment.destroy
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { head :no_content }
        format.js { render layout: false }
      end
    end


    private

      def appointments_params
        params.require(:appointment).permit(:date, :doctor_id, :patient_id, :time_slot_id, :status,
        note_attributes: [:id, :description])
      end

      def find_current_appointment
        @appointment = Appointment.find(params[:id])
      end

      def check_available_appointment(appointments_params)
        doctor = User.find_by(id: appointments_params["doctor_id"])
        appointment = doctor.patient_appointments.find_by(date: appointments_params["date"], time_slot_id: appointments_params["time_slot_id"])
        appointment ? false : true
      end
    end

app/views/appointments/destroy.js.erb
console.log('Binding event');
$('.delete_apponintment').bind('ajax:success', function() {
  console.log('fading the element: ', $(this).closest('tr')); 
  $(this).closest('tr').fadeOut();
});

app/views/appointments/edit.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

    <ul>
    <% @appointment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
    </div>
  <% end %>

  <% if current_user.role == 'patient' %>
    <div >
      <%= f.label :time_slot %>
      <%= f.collection_select :time_slot_id, @time_slots, :id, :slot %>
    </div>

    <div >
      <%= f.label :doctor %>
      <%= f.collection_select :doctor_id, @all_doctors, :id, :first_name %>
    </div>

    <div >
      <%= f.label :date %>
      <%= f.date_field :date %>
    </div>
    
  <% else %>
    <div >
      <%= f.label :status %>
      <%= f.select :status, ['pending', 'accepted', 'cancelled'] %>
    </div>
  <% end %>

  <div >
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1 class="well">My Upcoming Appointments</h1>

<% if current_user.role == 'patient' %>
  <%= link_to 'New appointment', new_appointment_path %><br>
  <% if @appointments.blank? %>
    <p>No appointments found.</p>
  <% else %>
    <tr>
      <th>Date</th>
      <th>Status</th>
      <th>Doctor</th>
      <th colspan="2"> </th>
    </tr>
    <br>

    <% @appointments.each do |appointment| %>
      <tr>
        <br>
        <td><%= appointment.date %></td>
        <td><%= appointment.status %></td>
        <td><%= appointment.doctor.first_name %></td>
      </tr>
      <tr>
        <td><%= link_to 'Show', appointment_path(appointment) %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment_path(appointment), method: :delete,data: { confirm: 'Are you sure?' }, :remote => true, class: "btn btn-primary btn-sm delete_appointment" %></td>
      </tr>
    <% end %>
  <% end %>
<% else %>

<%= link_to 'Edit doctor_specification', edit_doctor_specification_path(current_user) %><br>
	<% if @appointments.blank? %>
		<p>No appointments found.</p>
	<% else %>
    <tr>
      <th>Date</th>
      <th>Status</th>
      <th>Name</th>
      <th colspan="2"> </th>
    </tr>

    <% @appointments.each do |appointment| %>
      <br>
      <tr>
        <td><%= appointment.date %></td>
        <td><%= appointment.status %></td>
        <td><%= appointment.patient.first_name %></td>
      </tr>
      <tr>
        <td><%= link_to 'Show', appointment_path(appointment) %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment_path(appointment), method: :delete,data: { confirm: 'Are you sure?' }, :remote => true, class: "btn btn-primary btn-sm delete_appointment" %></td>
      </tr>
    <% end %>
  <% end %>
<% end %>
</div>
 

app/views/appointments/new.html.erb
<%= form_for @appointment do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

    <ul>
    <% @appointment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
    </div>
  <% end %>

  <div >
    <%= f.label :time_slot %>
    <%= f.collection_select :time_slot_id, @time_slots, :id, :slot %>
  </div>

  <div >
    <%= f.label :doctor %>
    <%= f.collection_select :doctor_id, @doctors, :id, :first_name %>
  </div>

  <div >
    <%= f.label :date %>
    <%= f.date_field :date %>
  </div>

  <%= f.fields_for :note do |note_form| %>
    <div >
      <%= note_form.label :description %>
      <%= note_form.text_field :description %>
    </div>
  <% end %>
  

  <div >
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"></p>

<p>
  <strong>Patient Name:</strong>
  <%= @appointment.patient.first_name %>
</p>
<p>
  <strong>Time:</strong>
  <%= @appointment.time_slot.slot %>
</p>
<p>
  <strong>Status:</strong>
  <%= @appointment.status %>
</p>
<p>
  <strong>Date:</strong>
  <%= @appointment.date %>
</p>

 <% if @appointment.note %>
   <h2>Notes</h2>																																																																					
   <%= render @appointment.note, appointment: @appointment %>
  <% end %> 

|
<%= link_to 'Back', appointments_path %>